apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wy4uret24-go 
  janus-idp.io/tekton: wy4uret24-go
  backstage.io/kubernetes-id: wy4uret24-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wy4uret24-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml