apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wy4uret24-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wy4uret24-go 
  name: wy4uret24-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wy4uret24-go 
